### ISSUE TITLE
github action을 통한 CI/CD

### ISSUE THREAD

**Issue by dos-m0nk3y** [osamhack2022-v2/WEB_CLOUD_OmilZomil_NAVYeffect#114]
github action을 통한 CI/CD

**Comment by Jun0zo** [comment]
vscode에서 reference볼 수 있는 extension이 있나요?

**Comment by greenrain78** [comment]
동작 과정
1. github action으로 ssh 스크립트 실행
2. oracle 경유 서버에 접속
3. run_github_action.sh 파일을 실행하여 117서버에 접속
4. 117 서버에서 run_a.sh 스크립트를 실행
5. 프로젝트 폴더에서 github_action.sh 를 실행하여 최신 코드로 업데이트 후 배포

**Comment by greenrain78** [comment]
배포서버(117) 의 브랜치는 리뷰 후 dev/cicd에서 development로 변경하겠습니다.
