### ISSUE TITLE
웹 rtc 테스트

### ISSUE THREAD

**Issue by HeoTaeRyang** [osamhack2022-v2/WEB_CLOUD_OmilZomil_NAVYeffect#195]
사진, 군종류, 파츠들 결과값, 파츠들 위치 좌표
예 : [ 사진, 해군, true, true, true, false, 좌표값4개x4]

위와 같은 더미 데이터 전송 해봐주십쇼

**Comment by greenrain78** [comment]
webrtc 디버그 페이지 개발 요청
1. url 입력을 받아서 socket 통신할 url 을 변경

**Comment by greenrain78** [comment]
2. 이미지를 포함한 값을 json형태로 전달
2.1. 입력란을 만들어 json안에 다른 데이터도 포함시킬 수 있도록 요청

**Comment by greenrain78** [comment]
상태 코드도 전달 완료
