### ISSUE TITLE
웹 rtc 통신 데이터 형식 예시

### ISSUE THREAD

**Issue by HeoTaeRyang** [osamhack2022-v2/WEB_CLOUD_OmilZomil_NAVYeffect#254]
위병소 목록(백->프론트)
{
    type : "list",
    list : ["1정문","2정문"]
}

실시간 사진(프론트->백)
{
    photo : 사진,
    name : "1정문"
}

결과물(백->프론트)
{
    type : "result",
    photo : boxing된 사진,
    kind : "black",                  //blue:근무복, green:전투복
    hair : true,
    nametag : true,
    leveltag : true,
    muffler : true,
    neck : false,
}                                            //kind:옷 종류, hair:두발, nametag:이름표, leveltag:계급장, muffler:마후라, neck:네카치프&링, flag:태극기
                                             //옷 종류와 상관있는 파츠들만

**Comment by greenrain78** [comment]
해당 내용에 맞게 backend에서 전달 완료
