### ISSUE TITLE
휴가 삭제 버그delete(/vacation/{vacation_id})

### ISSUE THREAD

**Issue by biyotteu** [osamhack2022-v2/WEB_CLOUD_OmilZomil_NAVYeffect#338]
omil-omilzomil-1  | ERROR:    Exception in ASGI application
omil-omilzomil-1  | Traceback (most recent call last):
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
omil-omilzomil-1  |     result = await app(  # type: ignore[func-returns-value]
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
omil-omilzomil-1  |     return await self.app(scope, receive, send)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
omil-omilzomil-1  |     await super().__call__(scope, receive, send)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
omil-omilzomil-1  |     await self.middleware_stack(scope, receive, send)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
omil-omilzomil-1  |     raise exc
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
omil-omilzomil-1  |     await self.app(scope, receive, _send)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
omil-omilzomil-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
omil-omilzomil-1  |     await self.app(scope, receive, send)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
omil-omilzomil-1  |     raise exc
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
omil-omilzomil-1  |     await self.app(scope, receive, sender)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
omil-omilzomil-1  |     raise e
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
omil-omilzomil-1  |     await self.app(scope, receive, send)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 680, in __call__
omil-omilzomil-1  |     await route.handle(scope, receive, send)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle
omil-omilzomil-1  |     await self.app(scope, receive, send)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
omil-omilzomil-1  |     response = await func(request)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
omil-omilzomil-1  |     raw_response = await run_endpoint_function(
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
omil-omilzomil-1  |     return await run_in_threadpool(dependant.call, **values)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
omil-omilzomil-1  |     return await anyio.to_thread.run_sync(func, *args)
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
omil-omilzomil-1  |     return await get_asynclib().run_sync_in_worker_thread(
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
omil-omilzomil-1  |     return await future
omil-omilzomil-1  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
omil-omilzomil-1  |     result = context.run(func, *args)
omil-omilzomil-1  |   File "/backend/src/./app/api/endpoints/vacation.py", line 48, in delete_vacation
omil-omilzomil-1  |     return crud.delete_vacation(db, vacation_id)
omil-omilzomil-1  |   File "/backend/src/./app/crud/vacation.py", line 75, in delete_vacation
omil-omilzomil-1  |     elif vacation.is_approved is True:
omil-omilzomil-1  | AttributeError: 'Query' object has no attribute 'is_approved'

**Comment by dos-m0nk3y** [comment]
#339 오류 해결완료
