### ISSUE TITLE
회원탈퇴 에러(422)

### ISSUE THREAD

**Issue by biyotteu** [osamhack2022-v2/WEB_CLOUD_OmilZomil_NAVYeffect#350]
<img width="1017" alt="스크린샷 2022-10-22 오전 12 00 33" src="https://user-images.githubusercontent.com/32426765/197226837-ddb0ceeb-b80d-4624-98e8-3caf19a8943b.png">
<img width="540" alt="스크린샷 2022-10-22 오전 12 00 54" src="https://user-images.githubusercontent.com/32426765/197226911-de8e2836-b82e-454c-9a83-4abe59f70a0a.png">

**Comment by dos-m0nk3y** [comment]
Response body도 같이 보내주세요.

**Comment by dos-m0nk3y** [comment]
요청이 JSON으로 보내지지 않았을 경우 생기는 오류.
요청 Header를 JSON으로 잡는것으로 해결 완료.
